---

- apt_key:
  keyserver: keyserver.ubuntu.com
  id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- apt_repository:
  repo: deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/
  state: present

- name: install r
  sudo: yes
  apt: name={{item}} state=present
  with_items:
    - r-base
    - r-base-dev
