---

- hosts: localhost
  connection: local
  sudo: no
  vars:
    whoami: "{{ lookup('env', 'USER') }}"
    user_home: "{{ lookup('env', 'HOME') }}"
    git_user_name: "jennadaly"
    git_user_email: "jenna.m.daly@gmail.com"
  roles:
    - basic
    - r
    - dev
